ALTER TABLE "player_games_stats" ADD COLUMN "plate_appearances" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "strikeouts_batted" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "hit_by_pitch" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "singles" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "doubles" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "triples" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "one_hr" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "two_hr" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "three_hr" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "grand_slams" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "total_bases" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "sac_flies" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "start_hits" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "stars_used_batting" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "stolen_bases" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "caught_stealing" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "steal_attempts" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "putout" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "assist" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "fielding_errors" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "buddy_jump_putouts" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "buddy_jump_attempts" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "double_plays" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "triple_plays" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "bobbles" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "batters_faced" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "pitches" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "strikes" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "balls" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "bean_balls" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "hits_allowed" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "singles_allowed" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "doubles_allowed" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "triples_allowed" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "home_runs_allowed" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "inherited_runs" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "star_pitches" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "stars_used_pitching" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "pickoffs" integer;--> statement-breakpoint
ALTER TABLE "player_games_stats" ADD COLUMN "pickoff_attempts" integer;